### PR TITLE
Enable Windows

### PR DESCRIPTION
**Pull request by jeongseok-meta**
Just to see if Windows build works as it is

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @traversaro - I saw you had some lapack issues on Windows before, do you have any clue what’s going on here?

**Comment by traversaro** [comment]
> Hi @traversaro - I saw you had some lapack issues on Windows before, do you have any clue what’s going on here?

The error is:

~~~
%PREFIX%\Library\include\lapack.h(97,26): error C2065: 'LAPACK_S_SELECT2': undeclared identifier (compiling source file %SRC_DIR%\cpp\open3d\core\linalg\LeastSquaresCPU.cpp) [%SRC_DIR%\build\cpp\open3d\core\core.vcxproj]
%PREFIX%\Library\include\lapack.h(97,42): error C2513: 'int': no variable declared before '=' (compiling source file %SRC_DIR%\cpp\open3d\core\linalg\LeastSquaresCPU.cpp) [%SRC_DIR%\build\cpp\open3d\core\core.vcxproj]
  LU.cpp
  PhongShader.cpp
%PREFIX%\Library\include\lapack.h(97,42): fatal error C1903: unable to recover from previous error(s); stopping compilation (compiling source file %SRC_DIR%\cpp\open3d\core\linalg\LeastSquaresCPU.cpp) [%SRC_DIR%\build\cpp\open3d\core\core.vcxproj]
  INTERNAL COMPILER ERROR in 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\CL.exe'
      Please choose the Technical Support command on the Visual C++
      Help menu, or open the Technical Support help file for more information
~~~

unfortunately I never saw it (and I can't find anything on a similar error on GitHub).

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Hi @jeongseok-meta - I pushed this a little forward, but I don't have a Windows machine and now got stuck with this:
```
LINK : fatal error LNK1181: cannot open input file 'stdc++.lib' [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
```

Do you have time to look into it?

**Comment by jeongseok-meta** [comment]
Thank you for making the change so far! I'm also relying on CI, but let me take a look.

**Comment by jeongseok-meta** [comment]
libzmq.pc seems to add it:

```
prefix=C:/Users/jeongseok/dev/tmp/test_stdc/.pixi/envs/default/Library
exec_prefix=C:/Users/jeongseok/dev/tmp/test_stdc/.pixi/envs/default/Library
libdir=C:/Users/jeongseok/dev/tmp/test_stdc/.pixi/envs/default/Library/lib
includedir=C:/Users/jeongseok/dev/tmp/test_stdc/.pixi/envs/default/Library/include

Name: libzmq
Description: 0MQ c++ library
Version: 4.3.5
Libs: -L${libdir} -lzmq
Libs.private: -lstdc++ 
Requires.private: 
Cflags: -I${includedir} 
```

**Comment by jeongseok-meta** [comment]
We may need to change this line to conditionally add `-lstdc++`, excluding it for windows:

https://github.com/zeromq/libzmq/blob/v4.3.5/src/libzmq.pc.in#L10

**Comment by jeongseok-meta** [comment]
```
2024-11-13T16:37:49.0105887Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzOpen64 [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0148503Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzClose [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0150211Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzGetGlobalInfo64 [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0151253Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzOpenCurrentFilePassword [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0152307Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzReadCurrentFile [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0153172Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzCloseCurrentFile [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0153900Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzGetCurrentFileInfo64 [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0154589Z ExtractZIP.obj : error LNK2001: unresolved external symbol unzGoToNextFile [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.0155290Z %SRC_DIR%\build\bin\Release\Open3D.dll : fatal error LNK1120: 8 unresolved externals [%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj]
2024-11-13T16:37:49.1420873Z Done Building Project "%SRC_DIR%\build\cpp\open3d\Open3D.vcxproj" (default targets) -- FAILED.
2024-11-13T16:37:49.1435019Z Done Building Project "%SRC_DIR%\build\cpp\pybind\pybind.vcxproj" (default targets) -- FAILED.
2024-11-13T16:37:49.1445544Z Done Building Project "%SRC_DIR%\build\cpp\pybind\python-package.vcxproj" (default targets) -- FAILED.
2024-11-13T16:37:49.1463526Z Done Building Project "%SRC_DIR%\build\cpp\pybind\pip-package.vcxproj" (default targets) -- FAILED.
2024-11-13T16:37:49.1476562Z Done Building Project "%SRC_DIR%\build\cpp\pybind\install-pip-package.vcxproj" (default targets) -- FAILED.
2024-11-13T16:37:49.1514947Z 
2024-11-13T16:37:49.1515912Z Build FAILED.
```

**Comment by Tobias-Fischer** [comment]
Thanks for pushing this further! If the `minizip` fix works, we should also adapt it for linux/osx; the more we can unvendor, the better.

**Comment by jeongseok-meta** [comment]
Sounds good! I may need to switch to other work, so feel free to take over from here. Otherwise, I'd be able to continue tomorrow or later.

**Comment by Tobias-Fischer** [comment]
I've just opened https://github.com/conda-forge/zeromq-feedstock/pull/78 so we can continue to use the conda-forge version hopefully.

**Comment by Tobias-Fischer** [comment]
Hmmm I'm a bit confused here:
```
  ERROR (open3d,Lib/site-packages/open3d/cpu/pybind.cp310-win_amd64.pyd): $RPATH/Open3D.dll not found in packages, sysroot(s) nor the missing_dso_whitelist.
.. is this binary repackaging?
```

However, the Open3D.dll lives in the same folder .. `Lib/site-packages/open3d/cpu/Open3D.dll`.

**Comment by jeongseok-meta** [comment]
It seems the `Open3D.dll` path is resolved, but now it fails the import test with no useful error messages:

```
2024-11-14T00:56:13.9529284Z import: 'open3d'
2024-11-14T00:56:15.3111297Z import: 'open3d'
2024-11-14T00:56:16.9632911Z WARNING: Tests failed for open3d-0.18.0-py310h894ec0d_13.conda - moving package to D:\bld\broken
2024-11-14T00:56:17.0619564Z Traceback (most recent call last):
2024-11-14T00:56:17.0621833Z   File "D:\Miniforge\Lib\site-packages\conda_build\build.py", line 3483, in test
2024-11-14T00:56:17.0697735Z     utils.check_call_env(
2024-11-14T00:56:17.0699414Z   File "D:\Miniforge\Lib\site-packages\conda_build\utils.py", line 404, in check_call_env
2024-11-14T00:56:17.0709795Z     return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
2024-11-14T00:56:17.0712817Z            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-11-14T00:56:17.0714058Z   File "D:\Miniforge\Lib\site-packages\conda_build\utils.py", line 380, in _func_defaulting_env_to_os_environ
2024-11-14T00:56:17.0715726Z     raise subprocess.CalledProcessError(proc.returncode, _args)
2024-11-14T00:56:17.0717449Z subprocess.CalledProcessError: Command '['C:\\Windows\\system32\\cmd.exe', '/d', '/c', 'D:\\bld\\open3d_1731543226218\\test_tmp\\conda_test_runner.bat']' returned non-zero exit status 1.
2024-11-14T00:56:17.0718301Z 
2024-11-14T00:56:17.0719161Z During handling of the above exception, another exception occurred:
2024-11-14T00:56:17.0719655Z 
2024-11-14T00:56:17.0720287Z Traceback (most recent call last):
2024-11-14T00:56:17.0721538Z   File "D:\Miniforge\Scripts\conda-build-script.py", line 10, in <module>
2024-11-14T00:56:17.0722194Z     sys.exit(execute())
2024-11-14T00:56:17.0722746Z              ^^^^^^^^^
2024-11-14T00:56:17.0723323Z   File "D:\Miniforge\Lib\site-packages\conda_build\cli\main_build.py", line 589, in execute
2024-11-14T00:56:17.0736883Z     api.build(
2024-11-14T00:56:17.0738172Z   File "D:\Miniforge\Lib\site-packages\conda_build\api.py", line 209, in build
2024-11-14T00:56:17.0744926Z     return build_tree(
2024-11-14T00:56:17.0745688Z            ^^^^^^^^^^^
2024-11-14T00:56:17.0746567Z   File "D:\Miniforge\Lib\site-packages\conda_build\build.py", line 3670, in build_tree
2024-11-14T00:56:17.0758050Z     test(pkg, config=metadata.config.copy(), stats=stats)
2024-11-14T00:56:17.0759201Z   File "D:\Miniforge\Lib\site-packages\conda_build\build.py", line 3497, in test
2024-11-14T00:56:17.0771051Z     tests_failed(
2024-11-14T00:56:17.0771875Z   File "D:\Miniforge\Lib\site-packages\conda_build\build.py", line 3544, in tests_failed
2024-11-14T00:56:17.0782586Z     raise CondaBuildUserError("TESTS FAILED: " + os.path.basename(pkg))
2024-11-14T00:56:17.0783591Z conda_build.exceptions.CondaBuildUserError: TESTS FAILED: open3d-0.18.0-py310h894ec0d_13.conda
2024-11-14T00:56:26.4068781Z ##[error]Cmd.exe exited with code '1'.
```

Also, it's just warning, but two packages are installing the same file to the same location (which shouldn't be installed by both as it's a readme.txt though):

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::gl2ps-1.4.2-had7236b_1, conda-forge/win-64::libhwloc-2.11.1-default_h8125262_1000
  path: 'library/readme.txt'
```

**Comment by Tobias-Fischer** [comment]
I think the remaining issue is that the open3d.exe should live in `%PREFIX%\\Library\\bin\\`, not in `Scripts`

**Comment by Tobias-Fischer** [comment]
Let's wait for https://github.com/conda-forge/zeromq-feedstock/pull/78 and then merge

**Comment by jeongseok-meta** [comment]
Yay, it's finally green! Yeah, we could wait for it or fix it in a follow-up, as we already have a patch for it.

In the meantime, we might want to enable back the other platforms to make sure.

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Many thanks @jeongseok-meta!

**Comment by jeongseok-meta** [comment]
Pleasure working with you on this, @Tobias-Fischer! Thanks for merging!

**Pull request merged**
